#!/usr/bin/env php
<?php
require_once __DIR__.'/autoload.php';
if ($argc < 3) {
    die("Please pass two phars to diff them.\n");
}

$phars = [
    new \ParagonIE\Pharaoh\Pharaoh($argv[1], 'A.phar'),
    new \ParagonIE\Pharaoh\Pharaoh($argv[2], 'B.phar')
];

$diff = new \ParagonIE\Pharaoh\PharDiff($phars[0], $phars[1]);

$diff->printGitDiff();