#!/usr/bin/env php
<?php
require_once __DIR__.'/src/autoload.php';
$opts = \getopt('gdrpc::', [
    'git-diff', 'diff', 'report', 'pdf', 'check::'
]);

if ($argc < 3) {
    die("Please pass two phars to diff them.\n");
}

// The last two commands should be our two .phar files
$pharB = \array_pop($argv);
$pharA = \array_pop($argv);

$phars = [
    new \ParagonIE\Pharaoh\Pharaoh($pharA),
    new \ParagonIE\Pharaoh\Pharaoh($pharB)
];

$diff = new \ParagonIE\Pharaoh\PharDiff($phars[0], $phars[1]);

if (!empty($opts['c'])) {
    $diff->listChecksums($opts['c']);
} elseif (!empty($opts['check'])) {
    $diff->listChecksums($opts['check']);
} elseif (isset($opts['d']) || isset($opts['diff'])) {
    $diff->printGnuDiff();
} else {
    $diff->printGitDiff();
}